# Generated by Django 3.2.15 on 2023-11-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Необработанный'), ('prepair to ship', 'Сборка заказа'), ('delivery', 'Доставка заказа'), ('delivered', 'Товар доставлен')], db_index=True, default='unprocessed', max_length=50),
        ),
    ]
