# Generated by Django 3.2.15 on 2023-11-29 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20231129_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='called',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата и время прозвона заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время создания заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата и время доставки заказа'),
        ),
    ]
