# Generated by Django 3.2.15 on 2023-12-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличностью'), ('card', 'Электронно'), ('missed', 'Не указано')], db_index=True, default='Не указано', max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
